### ISSUE TITLE
Hide headerbar when fullscreen

### ISSUE THREAD

**Issue by cassidyjames** [cassidyjames/butler#12]
Much more useful for a kiosk mode

**Comment by Erudition** [comment]
How do we toggle this? I'm using GNOME, and now I have no way to close or resize the window. It also blocks my hot corner, so I can't go to the overview that way.

**Comment by Erudition** [comment]
Nevermind, found it in the source code, had to hit F11. Need an easier way to know, though, given that it starts fullscreen every time from then on...

**Comment by cassidyjames** [comment]
When you enter Fullscreen, there's a notification that you can hit Ctrl+F or F11 to toggle it; However, I'd like to implement an auto-revealing headerbar when you mouse to the top of the fullscreen window. I thought I had an issue open for that, but I didn't; I'll do that now!
