### ISSUE TITLE
Icon lacks contrast (too dark)

### ISSUE THREAD

**Issue by ralxxx** [cassidyjames/butler#20]
Thanks for Butler - this little, absolutely useful helper.
I recognise that the new icon is not very well recognizable since its last revamp - since the icon received its tailcoat. (see screenshot from a Gnome desktop below)

Ideally, improve contrast/modify colors being used or just leave the original HA icon.    

![Bildschirmfoto vom 2024-01-20 10-11-05](https://github.com/cassidyjames/butler/assets/36100882/376fbde4-ac57-4d24-9cdd-acc67f04478c)

**Comment by cassidyjames** [comment]
Yep, I am still not happy with where this is and will continue to follow/play with the suggestions at https://gitlab.gnome.org/Teams/Design/app-icon-requests/-/issues/30 to improve it
