### ISSUE TITLE
Main content window is just the regular HA webapp

### ISSUE THREAD

**Issue by Sabinno** [cassidyjames/butler#31]
I logged in to my server successfully, updated my totally bone stock HAOS to the latest version, and... uh... it's just a web app. It works, definitely, but it's just an Adwaita headerbar with rounded corners at the bottom that shows me the regular web interface. Looks nothing like the screenshots.

This feels like unintended behavior. I'm on stock Fedora 40, no relevant extensions (just GSConnect), and as mentioned I use unmodified HAOS that I just updated to 12.2.

I have HA behind NPM proxy, but all it does is reverse proxy to https.

**Comment by cassidyjames** [comment]
Yeah this app is a wrapper around whatever your Home Assistant dashboard is, just like how the official apps integrate your dashboard on desktop and mobile.

The screenshot is of my dashboard, but I suppose you're right that it could be a bit more clear to include a stock dashboard screenshot for clarity.

**Comment by Sabinno** [comment]
Oh! I get it now. I was under the impression, based on the screenshot, that it would use APIs to pull the data itself and re-render the cards and UI to natively fit the DE (the Android app does this to a limited degree).

This app is definitely still useful for quicker access to HA, don't get me wrong.

**Comment by cassidyjames** [comment]
No worries, I can see how it would appear that way since I've spent a lot of time making my dashboard look nice. :D

If you're curious, I'm using the new "Sections" view type for my dashboard with the "Material Rounded" theme from HACS. And then all the entities are just Tile cards. It works out nicely!

**Comment by sagebind** [comment]
> (the Android app does this to a limited degree)

Actually it doesn't; everything you see in the Android app is powered by the Lovelace UI coming from your HA server, with the exception of the "Companion app" settings menu, which is a native Android UI. If you open HA in a mobile web browser you will get the same mobile-friendly UI.
