### ISSUE TITLE
Regarding header bar in dark mode

### ISSUE THREAD

**Issue by ignisf** [cassidyjames/butler#40]
Hey, I was wondering if you would be open to a PR that makes the header bar use the default dark theme colour when dark mode is selected for GTK?

https://github.com/cassidyjames/butler/blob/cb4ed9e809928ddd23cd681a924b6aa72051e089/data/style.css#L1-L2

**Comment by cassidyjames** [comment]
Yes! My eventual goal is actually to provide a configurable light/dark color, unless I can grab it reliably from the page without much overhead.

**Comment by cassidyjames** [comment]
@ignisf I might have a little something for you in the next release:

![Screenshot showing separate light and dark headerbar color settings](https://github.com/user-attachments/assets/bd019471-fd1d-4efd-a389-2ac70fda6431)
