### ISSUE TITLE
Unique icon

### ISSUE THREAD

**Issue by cassidyjames** [cassidyjames/butler#5]
I called this Butler (for Home Assistant) to distinguish it from being an official Home Assistant companion app, but it would be best to have a distinct icon as well. My goals for an icon are:

- Feels at home on GNOME (e.g. uses the GNOME guidelines)
- Feels related to Home Assistant (the house shape and blue color are strong elements here)
- Not just Home Assistant but in GNOME style
- Maybe something related to a butler, e.g. a bowtie, serving platter, or something?

**Comment by MylesGit** [comment]
Have you requested an icon from the [Gnome GitLab](https://gitlab.gnome.org/Teams/Design/app-icon-requests)?

**Comment by cassidyjames** [comment]
Yes. https://gitlab.gnome.org/Teams/Design/app-icon-requests/-/issues/30
